on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - '**'
      

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - name: Format branch name
       id: format
       run: echo "::set-output name=branch::$(echo ${{ github.ref_name }} | sed 's/\//-/g')"
     
     - name: Comment on PR
       uses: actions/github-script@v6
       with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! ${{ steps.format.outputs.branch }}'
            })